/**
 * KNOUX-X — VIDEO STUDIO D10/D11 EDIT PLAN
 *
 * The EditPlan is the normalized, immutable execution record of an approved
 * AI edit (Amendment 18 / Rule XVII). It is operation-graph truth:
 *
 *   PROJECT → OPERATION GRAPH (EditPlan) → REPLAY → PROJECT'
 *
 * Replay MUST NOT re-invoke any AI model. All operations are pure timeline
 * mutations expressed over the multitrack model
 * (src/core/creative/multitrackProject.ts).
 */

import type {
  MultitrackProject,
  TimelineAudioProperties,
  TimelineItem,
  TimelineItemTransform,
  TimelineKeyframe,
  TimelineTextProperties,
  TimelineTransition,
} from '../../creative/multitrackProject';

export const EDIT_PLAN_SCHEMA = 'knoux-edit-plan' as const;
export const EDIT_PLAN_VERSION = 1 as const;

export type EditPlanSource =
  | 'ai-proposal'
  | 'local-rule';

/**
 * Ordered edit operations. Every op carries an explicit id; parameters are
 * exact values, never generated by replay (replay just executes them).
 */
export type EditOperation =
  | { op: 'insert-item'; id: string; item: TimelineItem }
  | { op: 'move-item'; id: string; itemId: string; targetTrackId: string; timelineStart: number }
  | { op: 'delete-items'; id: string; itemIds: string[] }
  | { op: 'split-item'; id: string; itemId: string; timelineTime: number; rightId: string }
  | { op: 'trim-item'; id: string; itemId: string; timelineStart: number; duration: number; sourceIn: number; sourceOut: number }
  | { op: 'patch-transform'; id: string; itemId: string; patch: Partial<TimelineItemTransform> }
  | { op: 'patch-audio'; id: string; itemId: string; patch: Partial<TimelineAudioProperties> }
  | { op: 'update-text'; id: string; itemId: string; text: TimelineTextProperties }
  | { op: 'upsert-keyframe'; id: string; itemId: string; keyframe: TimelineKeyframe }
  | { op: 'remove-keyframe'; id: string; itemId: string; keyframeId: string }
  | { op: 'set-transition'; id: string; itemId: string; side: 'in' | 'out'; transition: TimelineTransition | null };

/** Asset identity surfaced for auditing replay assumptions (spec §3.1). */
export interface EditPlanAssetIdentity {
  itemId: string;
  sourcePath: string | null;
  fileSize: number;
  modifiedAt: number;
  /** Full-file SHA-256 when available; optional bounded pre-check otherwise. */
  sha256?: string;
}

/** Environment assumptions required for deterministic replay. */
export interface EditPlanEnvironment {
  timelineSchema: 'knoux-multitrack';
  timelineVersion: 1;
  /** Artificial-capability note; replay is CPU-only, no GPU assumption. */
  renderBackend: 'local-ffmpeg';
}

export interface EditPlan {
  schema: typeof EDIT_PLAN_SCHEMA;
  version: typeof EDIT_PLAN_VERSION;
  planId: string;
  label: string;
  source: EditPlanSource;
  /** sourceProjectRevision is the immutable identity of the source project. */
  sourceProjectRevision: string;
  sourceProjectFingerprint: string;
  operations: EditOperation[];
  assetIdentities: EditPlanAssetIdentity[];
  variantContext: { variantId?: string; sourceVariantId?: string };
  environment: EditPlanEnvironment;
  evidence: {
    proposalId?: string;
    prompt?: string;
    model?: string;
    createdAt: string;
  };
  /** New plan revision per change (Amendment 18); never mutate in place. */
  revision: number;
}

export interface EditPlanRecord extends EditPlan {
  approvedAt: string;
  execution: {
    appliedAt: string | null;
    outputProjectFingerprint: string | null;
    applied: boolean;
    error: string | null;
  };
}

function assertId(value: unknown, label: string): string {
  if (typeof value !== 'string' || value.trim().length === 0 || value.length > 200) {
    throw new TypeError(`${label} must be a non-empty identifier.`);
  }
  return value.trim();
}

function assertFinite(value: unknown, label: string): number {
  const number = typeof value === 'number' ? value : Number.NaN;
  if (!Number.isFinite(number)) throw new TypeError(`${label} must be finite.`);
  return number;
}

/** Deterministic canonical serialization (sorted keys) for fingerprints. */
export function canonicalSerialize(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map((entry) => canonicalSerialize(entry)).join(',')}]`;
  const record = value as Record<string, unknown>;
  const keys = Object.keys(record).sort();
  return `{${keys.map((key) => `${JSON.stringify(key)}:${canonicalSerialize(record[key])}`).join(',')}}`;
}

/** Bounded fast fingerprint (FNV-1a 32-bit hex). Not a collision-safe hash. */
export function quickFingerprint(text: string): string {
  let hash = 0x811c9dc5;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, '0');
}

/**
 * Project fingerprint: canonical JSON of the whole project hashed with the
 * bounded quick fingerprint. For authoritative identity (contentHash) use
 * full SHA-256 at the storage layer (spec §3.1).
 */
export function projectFingerprint(project: MultitrackProject): string {
  const revision = {
    id: project.id,
    updatedAt: project.updatedAt,
    settings: project.settings,
    tracks: project.tracks.map((track) => ({
      id: track.id,
      kind: track.kind,
      order: track.order,
      locked: track.locked,
      hidden: track.hidden,
      muted: track.muted,
      solo: track.solo,
      volume: track.volume,
      pan: track.pan,
      items: track.items.map((item) => ({
        id: item.id,
        trackId: item.trackId,
        kind: item.kind,
        timelineStart: item.timelineStart,
        duration: item.duration,
        sourceIn: item.sourceIn,
        sourceOut: item.sourceOut,
        playbackRate: item.playbackRate,
        transform: item.transform,
        audio: item.audio,
        text: item.text,
        keyframes: item.keyframes,
        transitionIn: item.transitionIn,
        transitionOut: item.transitionOut,
        locked: item.locked,
      })),
    })),
  };
  return quickFingerprint(canonicalSerialize(revision));
}

/** Immutable project revision string: `projectId@updatedAt@fingerprint`. */
export function projectRevision(project: MultitrackProject): string {
  return `${project.id}@${project.updatedAt}@${projectFingerprint(project)}`;
}

function validateOperation(operation: EditOperation): void {
  assertId(operation.id, 'Operation id');
  switch (operation.op) {
    case 'insert-item':
      if (!operation.item || typeof operation.item !== 'object') throw new TypeError('insert-item requires an item.');
      if (typeof operation.item.id !== 'string' || operation.item.id.length === 0) throw new TypeError('insert-item item.id is invalid.');
      if (typeof operation.item.trackId !== 'string' || operation.item.trackId.length === 0) throw new TypeError('insert-item item.trackId is invalid.');
      break;
    case 'move-item':
      assertId(operation.itemId, 'move-item itemId');
      assertId(operation.targetTrackId, 'move-item targetTrackId');
      assertFinite(operation.timelineStart, 'move-item timelineStart');
      break;
    case 'delete-items':
      if (!Array.isArray(operation.itemIds) || operation.itemIds.length === 0) throw new TypeError('delete-items requires item ids.');
      operation.itemIds.forEach((itemId) => assertId(itemId, 'delete-items itemId'));
      break;
    case 'split-item':
      assertId(operation.itemId, 'split-item itemId');
      assertFinite(operation.timelineTime, 'split-item timelineTime');
      assertId(operation.rightId, 'split-item rightId');
      break;
    case 'trim-item':
      assertId(operation.itemId, 'trim-item itemId');
      assertFinite(operation.timelineStart, 'trim-item timelineStart');
      assertFinite(operation.duration, 'trim-item duration');
      assertFinite(operation.sourceIn, 'trim-item sourceIn');
      assertFinite(operation.sourceOut, 'trim-item sourceOut');
      if (operation.sourceOut <= operation.sourceIn) throw new RangeError('trim-item sourceOut must be after sourceIn.');
      break;
    case 'patch-transform':
    case 'patch-audio':
      assertId(operation.itemId, 'patch itemId');
      if (!operation.patch || typeof operation.patch !== 'object') throw new TypeError('patch is required.');
      break;
    case 'update-text':
      assertId(operation.itemId, 'update-text itemId');
      if (!operation.text || typeof operation.text !== 'object') throw new TypeError('update-text requires text properties.');
      break;
    case 'upsert-keyframe':
      assertId(operation.itemId, 'upsert-keyframe itemId');
      if (!operation.keyframe || !operation.keyframe.id || !operation.keyframe.property) throw new TypeError('upsert-keyframe requires a complete keyframe.');
      break;
    case 'remove-keyframe':
      assertId(operation.itemId, 'remove-keyframe itemId');
      assertId(operation.keyframeId, 'remove-keyframe keyframeId');
      break;
    case 'set-transition':
      assertId(operation.itemId, 'set-transition itemId');
      if (operation.side !== 'in' && operation.side !== 'out') throw new TypeError('set-transition side must be in|out.');
      if (operation.transition !== null) {
        if (!operation.transition.id || !operation.transition.kind) throw new TypeError('set-transition requires a complete transition.');
      }
      break;
    default:
      throw new TypeError('Unsupported edit operation.');
  }
}

/**
 * Validates a full plan and returns a sanitized clone. Throws TypeError on
 * any malformed field; runs the same structural checks the replay uses.
 */
export function parseEditPlan(value: unknown): EditPlan {
  if (!value || typeof value !== 'object') throw new TypeError('Edit plan must be an object.');
  const candidate = value as Partial<EditPlan>;
  if (candidate.schema !== EDIT_PLAN_SCHEMA || candidate.version !== EDIT_PLAN_VERSION) {
    throw new TypeError('Unsupported edit plan schema.');
  }
  const planId = assertId(candidate.planId, 'planId');
  if (typeof candidate.label !== 'string' || candidate.label.trim().length === 0 || candidate.label.length > 240) {
    throw new TypeError('Edit plan label is invalid.');
  }
  if (candidate.source !== 'ai-proposal' && candidate.source !== 'local-rule') throw new TypeError('Edit plan source is invalid.');
  const sourceProjectRevision = assertId(candidate.sourceProjectRevision, 'sourceProjectRevision');
  if (typeof candidate.sourceProjectFingerprint !== 'string' || !/^[0-9a-f]{8}$/.test(candidate.sourceProjectFingerprint)) {
    throw new TypeError('sourceProjectFingerprint is invalid.');
  }
  if (!Array.isArray(candidate.operations)) throw new TypeError('operations must be an array.');
  candidate.operations.forEach(validateOperation);
  const ids = new Set<string>();
  candidate.operations.forEach((operation) => {
    if (ids.has(operation.id)) throw new TypeError('Duplicate operation id.');
    ids.add(operation.id);
  });
  if (candidate.assetIdentities !== undefined && !Array.isArray(candidate.assetIdentities)) throw new TypeError('assetIdentities must be an array.');
  if (!candidate.evidence || typeof candidate.evidence.createdAt !== 'string') throw new TypeError('evidence.createdAt is required.');
  if (candidate.environment?.timelineSchema !== 'knoux-multitrack' || candidate.environment?.timelineVersion !== 1) {
    throw new TypeError('Unsupported plan environment.');
  }
  if (typeof candidate.revision !== 'number' || !Number.isInteger(candidate.revision) || candidate.revision < 1) {
    throw new TypeError('Plan revision must be a positive integer.');
  }
  return {
    schema: EDIT_PLAN_SCHEMA,
    version: EDIT_PLAN_VERSION,
    planId,
    label: candidate.label.trim(),
    source: candidate.source,
    sourceProjectRevision,
    sourceProjectFingerprint: candidate.sourceProjectFingerprint,
    operations: candidate.operations.map((operation) => ({ ...operation })),
    assetIdentities: (candidate.assetIdentities ?? []).map((identity) => ({ ...identity })),
    variantContext: {
      variantId: candidate.variantContext?.variantId,
      sourceVariantId: candidate.variantContext?.sourceVariantId,
    },
    environment: { ...candidate.environment },
    evidence: { ...candidate.evidence },
    revision: candidate.revision,
  };
}

export function createPlanEnvironment(): EditPlanEnvironment {
  return {
    timelineSchema: 'knoux-multitrack',
    timelineVersion: 1,
    renderBackend: 'local-ffmpeg',
  };
}