/**
 * KNOUX-X — VIDEO STUDIO D10/D11 EDIT PLAN
 *
 * The EditPlan is the normalized, immutable execution record of an approved
 * AI edit (Amendment 18 / Rule XVII). It is operation-graph truth:
 *
 *   PROJECT → OPERATION GRAPH (EditPlan) → REPLAY → PROJECT'
 *
 * Replay MUST NOT re-invoke any AI model. All operations are pure timeline
 * mutations expressed over the multitrack model
 * (src/core/creative/multitrackProject.ts).
 */

import type {
  MultitrackProject,
  TimelineAudioProperties,
  TimelineItem,
  TimelineItemTransform,
  TimelineKeyframe,
  TimelineTextProperties,
  TimelineTransition,
} from '../../creative/multitrackProject';

export const EDIT_PLAN_SCHEMA = 'knoux-edit-plan' as const;
export const EDIT_PLAN_VERSION = 1 as const;

export type EditPlanSource =
  | 'ai-proposal'
  | 'local-rule';

/**
 * Ordered edit operations. Every op carries an explicit id; parameters are
 * exact values, never generated by replay (replay just executes them).
 */
export type EditOperation =
  | { op: 'insert-item'; id: string; item: TimelineItem }
  | { op: 'move-item'; id: string; itemId: string; targetTrackId: string; timelineStart: number }
  | { op: 'delete-items'; id: string; itemIds: string[] }
  | { op: 'split-item'; id: string; itemId: string; timelineTime: number; rightId: string }
  | { op: 'trim-item'; id: string; itemId: string; timelineStart: number; duration: number; sourceIn: number; sourceOut: number }
  | { op: 'patch-transform'; id: string; itemId: string; patch: Partial<TimelineItemTransform> }
  | { op: 'patch-audio'; id: string; itemId: string; patch: Partial<TimelineAudioProperties> }
  | { op: 'update-text'; id: string; itemId: string; text: TimelineTextProperties }
  | { op: 'upsert-keyframe'; id: string; itemId: string; keyframe: TimelineKeyframe }
  | { op: 'remove-keyframe'; id: string; itemId: string; keyframeId: string }
  | { op: 'set-transition'; id: string; itemId: string; side: 'in' | 'out'; transition: TimelineTransition | null };

/** Asset identity surfaced for auditing replay assumptions (spec §3.1). */
export interface EditPlanAssetIdentity {
  itemId: string;
  sourcePath: string | null;
  fileSize: number;
  modifiedAt: number;
  /** Full-file SHA-256 when available; optional bounded pre-check otherwise. */
  sha256?: string;
}

/** Environment assumptions required for deterministic replay. */
export interface EditPlanEnvironment {
  timelineSchema: 'knoux-multitrack';
  timelineVersion: 1;
  /** Artificial-capability note; replay is CPU-only, no GPU assumption. */
  renderBackend: 'local-ffmpeg';
}

export interface EditPlan {
  schema: typeof EDIT_PLAN_SCHEMA;
  version: typeof EDIT_PLAN_VERSION;
  planId: string;
  label: string;
  source: EditPlanSource;
  /** sourceProjectRevision is the immutable identity of the source project. */
  sourceProjectRevision: string;
  sourceProjectFingerprint: string;
  operations: EditOperation[];
  assetIdentities: EditPlanAssetIdentity[];
  variantContext: { variantId?: string; sourceVariantId?: string };
  environment: EditPlanEnvironment;
  evidence: {
    proposalId?: string;
    prompt?: string;
    model?: string;
    createdAt: string;
  };
  /** New plan revision per change (Amendment 18); never mutate in place. */
  revision: number;
}

export interface EditPlanRecord extends EditPlan {
  approvedAt: string;
  execution: {
    appliedAt: string | null;
    outputProjectFingerprint: string | null;
    applied: boolean;
    error: string | null;
  };
}

function assertId(value: unknown, label: string): string {
  if (typeof value !== 'string' || value.trim().length === 0 || value.length > 200) {
    throw new TypeError(`${label} must be a non-empty identifier.`);
  }
  return value.trim();
}

function assertFinite(value: unknown, label: string): number {
  const number = typeof value === 'number' ? value : Number.NaN;
  if (!Number.isFinite(number)) throw new TypeError(`${label} must be finite.`);
  return number;
}

function assertNonNegative(value: unknown, label: string): number {
  const number = assertFinite(value, label);
  if (number < 0) throw new RangeError(`${label} cannot be negative.`);
  return number;
}

function assertPositive(value: unknown, label: string): number {
  const number = assertFinite(value, label);
  if (number <= 0) throw new RangeError(`${label} must be positive.`);
  return number;
}

function assertEnum<T extends string>(value: unknown, allowed: readonly T[], label: string): T {
  if (typeof value !== 'string' || !(allowed as readonly string[]).includes(value)) {
    throw new TypeError(`${label} must be one of ${allowed.join(', ')}.`);
  }
  return value as T;
}

function assertColor(value: unknown, label: string): string {
  if (typeof value !== 'string' || value.length > 64 || !/^(#[0-9a-f]{3,8}|rgba?\([^)]*\)|transparent)$/i.test(value)) {
    throw new TypeError(`${label} is invalid.`);
  }
  return value;
}

const VALID_BLEND_MODES = ['normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten'] as const;
const VALID_KEYFRAME_PROPERTIES = ['positionX','positionY','scale','rotation','opacity','volume','cropLeft','cropTop','cropRight','cropBottom'] as const;
const VALID_EASING_MODES = ['linear','ease-in','ease-out','ease-in-out'] as const;
const VALID_TRANSITION_KINDS = ['cross-dissolve','fade-black','fade-white','dip-color','wipe','slide','push','zoom','blur'] as const;
const VALID_ITEM_KINDS = ['video','audio','image','text','subtitle','overlay','color'] as const;

function validateTransformPatch(patch: Record<string, unknown>): void {
  if ('positionX' in patch) assertFinite(patch.positionX, 'transform.positionX');
  if ('positionY' in patch) assertFinite(patch.positionY, 'transform.positionY');
  if ('scale' in patch) {
    const scale = assertFinite(patch.scale, 'transform.scale');
    if (scale <= 0 || scale > 100) throw new RangeError('transform.scale must be >0 and <=100.');
  }
  if ('rotation' in patch) assertFinite(patch.rotation, 'transform.rotation');
  if ('opacity' in patch) {
    const opacity = assertFinite(patch.opacity, 'transform.opacity');
    if (opacity < 0 || opacity > 1) throw new RangeError('transform.opacity must be between 0 and 1.');
  }
  if ('cropLeft' in patch) assertFinite(patch.cropLeft, 'transform.cropLeft');
  if ('cropTop' in patch) assertFinite(patch.cropTop, 'transform.cropTop');
  if ('cropRight' in patch) assertFinite(patch.cropRight, 'transform.cropRight');
  if ('cropBottom' in patch) assertFinite(patch.cropBottom, 'transform.cropBottom');
  if ('flipHorizontal' in patch && typeof patch.flipHorizontal !== 'boolean') throw new TypeError('transform.flipHorizontal must be boolean.');
  if ('flipVertical' in patch && typeof patch.flipVertical !== 'boolean') throw new TypeError('transform.flipVertical must be boolean.');
  if ('blendMode' in patch) assertEnum(patch.blendMode, VALID_BLEND_MODES, 'transform.blendMode');
}

function validateAudioPatch(patch: Record<string, unknown>): void {
  if ('volume' in patch) {
    const volume = assertFinite(patch.volume, 'audio.volume');
    if (volume < 0 || volume > 4) throw new RangeError('audio.volume must be between 0 and 4.');
  }
  if ('pan' in patch) {
    const pan = assertFinite(patch.pan, 'audio.pan');
    if (pan < -1 || pan > 1) throw new RangeError('audio.pan must be between -1 and 1.');
  }
  if ('fadeIn' in patch) assertNonNegative(patch.fadeIn, 'audio.fadeIn');
  if ('fadeOut' in patch) assertNonNegative(patch.fadeOut, 'audio.fadeOut');
  if ('muted' in patch && typeof patch.muted !== 'boolean') throw new TypeError('audio.muted must be boolean.');
}

function validateTextProperties(value: unknown): void {
  if (!value || typeof value !== 'object') throw new TypeError('text properties must be an object.');
  const text = value as Record<string, unknown>;
  if (typeof text.text !== 'string') throw new TypeError('text.text must be a string.');
  if (typeof text.fontFamily !== 'string' || text.fontFamily.length === 0) throw new TypeError('text.fontFamily is invalid.');
  assertPositive(text.fontSize, 'text.fontSize');
  assertFinite(text.fontWeight, 'text.fontWeight');
  assertColor(text.color, 'text.color');
  assertColor(text.strokeColor, 'text.strokeColor');
  assertFinite(text.strokeWidth, 'text.strokeWidth');
  assertColor(text.backgroundColor, 'text.backgroundColor');
  assertEnum(text.align, ['start','center','end'], 'text.align');
  assertEnum(text.direction, ['auto','ltr','rtl'], 'text.direction');
}

function validateKeyframe(value: unknown): void {
  if (!value || typeof value !== 'object') throw new TypeError('keyframe must be an object.');
  const keyframe = value as Record<string, unknown>;
  assertId(keyframe.id, 'keyframe id');
  assertEnum(keyframe.property, VALID_KEYFRAME_PROPERTIES, 'keyframe property');
  assertNonNegative(keyframe.time, 'keyframe time');
  assertFinite(keyframe.value, 'keyframe value');
  assertEnum(keyframe.easing, VALID_EASING_MODES, 'keyframe easing');
}

function validateTransition(value: unknown): void {
  if (!value || typeof value !== 'object') throw new TypeError('transition must be an object.');
  const transition = value as Record<string, unknown>;
  assertId(transition.id, 'transition id');
  assertEnum(transition.kind, VALID_TRANSITION_KINDS, 'transition kind');
  assertNonNegative(transition.duration, 'transition duration');
  if ('direction' in transition && transition.direction !== undefined) {
    assertEnum(transition.direction, ['left','right','up','down'], 'transition direction');
  }
  if ('color' in transition && transition.color !== undefined) assertColor(transition.color, 'transition color');
}

function validateTimelineItem(value: unknown): void {
  if (!value || typeof value !== 'object') throw new TypeError('Timeline item must be an object.');
  const item = value as Record<string, unknown>;
  assertId(item.id, 'Timeline item id');
  assertId(item.trackId, 'Timeline item trackId');
  assertEnum(item.kind, VALID_ITEM_KINDS, 'Timeline item kind');
  if (typeof item.name !== 'string' || item.name.trim().length === 0 || item.name.length > 240) throw new TypeError('Timeline item name is invalid.');
  assertNonNegative(item.timelineStart, 'Timeline item timelineStart');
  assertPositive(item.duration, 'Timeline item duration');
  assertNonNegative(item.sourceIn, 'Timeline item sourceIn');
  assertFinite(item.sourceOut, 'Timeline item sourceOut');
  const sourceIn = item.sourceIn as number;
  const sourceOut = item.sourceOut as number;
  if (sourceOut <= sourceIn) throw new RangeError('Timeline item sourceOut must be after sourceIn.');
  assertPositive(item.playbackRate, 'Timeline item playbackRate');
  if (!item.transform || typeof item.transform !== 'object') throw new TypeError('Timeline item transform is required.');
  validateTransformPatch(item.transform as Record<string, unknown>);
  // Require canonical transform fields to be present and valid for inserted items
  const transform = item.transform as Record<string, unknown>;
  if (!('positionX' in transform) || !('positionY' in transform) || !('scale' in transform) || !('rotation' in transform) || !('opacity' in transform)) {
    throw new TypeError('Timeline item transform is incomplete.');
  }
  if (!item.audio || typeof item.audio !== 'object') throw new TypeError('Timeline item audio is required.');
  validateAudioPatch(item.audio as Record<string, unknown>);
  const audio = item.audio as Record<string, unknown>;
  if (!('volume' in audio) || !('pan' in audio) || !('muted' in audio)) throw new TypeError('Timeline item audio is incomplete.');
  if (item.text !== null) {
    if (item.text !== undefined) validateTextProperties(item.text);
  }
  if (!Array.isArray(item.keyframes)) throw new TypeError('Timeline item keyframes must be an array.');
  for (const keyframe of item.keyframes as unknown[]) validateKeyframe(keyframe);
  if (item.transitionIn !== null && item.transitionIn !== undefined) validateTransition(item.transitionIn);
  if (item.transitionOut !== null && item.transitionOut !== undefined) validateTransition(item.transitionOut);
}

/** Deterministic canonical serialization (sorted keys) for fingerprints. */
export function canonicalSerialize(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map((entry) => canonicalSerialize(entry)).join(',')}]`;
  const record = value as Record<string, unknown>;
  const keys = Object.keys(record).sort();
  return `{${keys.map((key) => `${JSON.stringify(key)}:${canonicalSerialize(record[key])}`).join(',')}}`;
}

/** Bounded fast fingerprint (FNV-1a 32-bit hex). Not a collision-safe hash. */
export function quickFingerprint(text: string): string {
  let hash = 0x811c9dc5;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, '0');
}

/**
 * Project fingerprint: canonical JSON of the whole project hashed with the
 * bounded quick fingerprint. For authoritative identity (contentHash) use
 * full SHA-256 at the storage layer (spec §3.1).
 */
export function projectFingerprint(project: MultitrackProject): string {
  const revision = {
    id: project.id,
    updatedAt: project.updatedAt,
    settings: project.settings,
    tracks: project.tracks.map((track) => ({
      id: track.id,
      kind: track.kind,
      order: track.order,
      locked: track.locked,
      hidden: track.hidden,
      muted: track.muted,
      solo: track.solo,
      volume: track.volume,
      pan: track.pan,
      items: track.items.map((item) => ({
        id: item.id,
        trackId: item.trackId,
        kind: item.kind,
        timelineStart: item.timelineStart,
        duration: item.duration,
        sourceIn: item.sourceIn,
        sourceOut: item.sourceOut,
        playbackRate: item.playbackRate,
        transform: item.transform,
        audio: item.audio,
        text: item.text,
        keyframes: item.keyframes,
        transitionIn: item.transitionIn,
        transitionOut: item.transitionOut,
        locked: item.locked,
      })),
    })),
  };
  return quickFingerprint(canonicalSerialize(revision));
}

/** Immutable project revision string: `projectId@updatedAt@fingerprint`. */
export function projectRevision(project: MultitrackProject): string {
  return `${project.id}@${project.updatedAt}@${projectFingerprint(project)}`;
}

function validateOperation(operation: EditOperation): void {
  assertId(operation.id, 'Operation id');
  switch (operation.op) {
    case 'insert-item':
      validateTimelineItem(operation.item);
      break;
    case 'move-item':
      assertId(operation.itemId, 'move-item itemId');
      assertId(operation.targetTrackId, 'move-item targetTrackId');
      assertNonNegative(operation.timelineStart, 'move-item timelineStart');
      break;
    case 'delete-items':
      if (!Array.isArray(operation.itemIds) || operation.itemIds.length === 0) throw new TypeError('delete-items requires item ids.');
      operation.itemIds.forEach((itemId) => assertId(itemId, 'delete-items itemId'));
      break;
    case 'split-item':
      assertId(operation.itemId, 'split-item itemId');
      assertFinite(operation.timelineTime, 'split-item timelineTime');
      assertId(operation.rightId, 'split-item rightId');
      break;
    case 'trim-item':
      assertId(operation.itemId, 'trim-item itemId');
      assertNonNegative(operation.timelineStart, 'trim-item timelineStart');
      assertPositive(operation.duration, 'trim-item duration');
      assertNonNegative(operation.sourceIn, 'trim-item sourceIn');
      assertFinite(operation.sourceOut, 'trim-item sourceOut');
      if ((operation.sourceOut as number) <= (operation.sourceIn as number)) throw new RangeError('trim-item sourceOut must be after sourceIn.');
      break;
    case 'patch-transform':
      assertId(operation.itemId, 'patch-transform itemId');
      if (!operation.patch || typeof operation.patch !== 'object') throw new TypeError('patch-transform requires a patch object.');
      validateTransformPatch(operation.patch as Record<string, unknown>);
      if (Object.keys(operation.patch as Record<string, unknown>).length === 0) throw new TypeError('patch-transform patch cannot be empty.');
      break;
    case 'patch-audio':
      assertId(operation.itemId, 'patch-audio itemId');
      if (!operation.patch || typeof operation.patch !== 'object') throw new TypeError('patch-audio requires a patch object.');
      validateAudioPatch(operation.patch as Record<string, unknown>);
      if (Object.keys(operation.patch as Record<string, unknown>).length === 0) throw new TypeError('patch-audio patch cannot be empty.');
      break;
    case 'update-text':
      assertId(operation.itemId, 'update-text itemId');
      validateTextProperties(operation.text);
      break;
    case 'upsert-keyframe':
      assertId(operation.itemId, 'upsert-keyframe itemId');
      validateKeyframe(operation.keyframe);
      break;
    case 'remove-keyframe':
      assertId(operation.itemId, 'remove-keyframe itemId');
      assertId(operation.keyframeId, 'remove-keyframe keyframeId');
      break;
    case 'set-transition':
      assertId(operation.itemId, 'set-transition itemId');
      if (operation.side !== 'in' && operation.side !== 'out') throw new TypeError('set-transition side must be in|out.');
      if (operation.transition !== null) validateTransition(operation.transition);
      break;
    default:
      throw new TypeError('Unsupported edit operation.');
  }
}

/**
 * Validates a full plan and returns a sanitized clone. Throws TypeError on
 * any malformed field; runs the same structural checks the replay uses.
 */
export function parseEditPlan(value: unknown, sourceProject?: MultitrackProject): EditPlan {
  if (!value || typeof value !== 'object') throw new TypeError('Edit plan must be an object.');
  const candidate = value as Partial<EditPlan>;
  if (candidate.schema !== EDIT_PLAN_SCHEMA || candidate.version !== EDIT_PLAN_VERSION) {
    throw new TypeError('Unsupported edit plan schema.');
  }
  const planId = assertId(candidate.planId, 'planId');
  if (typeof candidate.label !== 'string' || candidate.label.trim().length === 0 || candidate.label.length > 240) {
    throw new TypeError('Edit plan label is invalid.');
  }
  if (candidate.source !== 'ai-proposal' && candidate.source !== 'local-rule') throw new TypeError('Edit plan source is invalid.');
  const sourceProjectRevision = assertId(candidate.sourceProjectRevision, 'sourceProjectRevision');
  if (typeof candidate.sourceProjectFingerprint !== 'string' || !/^[0-9a-f]{8}$/.test(candidate.sourceProjectFingerprint)) {
    throw new TypeError('sourceProjectFingerprint is invalid.');
  }
  if (!Array.isArray(candidate.operations)) throw new TypeError('operations must be an array.');
  candidate.operations.forEach(validateOperation);
  const ids = new Set<string>();
  candidate.operations.forEach((operation) => {
    if (ids.has(operation.id)) throw new TypeError('Duplicate operation id.');
    ids.add(operation.id);
  });
  if (candidate.assetIdentities !== undefined && !Array.isArray(candidate.assetIdentities)) throw new TypeError('assetIdentities must be an array.');
  if (!candidate.evidence || typeof candidate.evidence.createdAt !== 'string') throw new TypeError('evidence.createdAt is required.');
  if (candidate.environment?.timelineSchema !== 'knoux-multitrack' || candidate.environment?.timelineVersion !== 1) {
    throw new TypeError('Unsupported plan environment.');
  }
  if (typeof candidate.revision !== 'number' || !Number.isInteger(candidate.revision) || candidate.revision < 1) {
    throw new TypeError('Plan revision must be a positive integer.');
  }
  const plan: EditPlan = {
    schema: EDIT_PLAN_SCHEMA,
    version: EDIT_PLAN_VERSION,
    planId,
    label: candidate.label.trim(),
    source: candidate.source,
    sourceProjectRevision,
    sourceProjectFingerprint: candidate.sourceProjectFingerprint,
    operations: candidate.operations.map((operation) => ({ ...operation })),
    assetIdentities: (candidate.assetIdentities ?? []).map((identity) => ({ ...identity })),
    variantContext: {
      variantId: candidate.variantContext?.variantId,
      sourceVariantId: candidate.variantContext?.sourceVariantId,
    },
    environment: { ...candidate.environment },
    evidence: { ...candidate.evidence },
    revision: candidate.revision,
  };
  if (sourceProject) {
    const items = new Map(sourceProject.tracks.flatMap((track) => track.items.map((item) => [item.id, item] as const)));
    for (const operation of plan.operations) {
      if (operation.op !== 'upsert-keyframe') continue;
      const item = items.get(operation.itemId);
      if (!item) throw new RangeError(`Keyframe target item ${operation.itemId} does not exist.`);
      if (operation.keyframe.time > item.duration) {
        throw new RangeError(`Keyframe time cannot exceed item duration for ${operation.itemId}.`);
      }
    }
  }
  return plan;
}

export function createPlanEnvironment(): EditPlanEnvironment {
  return {
    timelineSchema: 'knoux-multitrack',
    timelineVersion: 1,
    renderBackend: 'local-ffmpeg',
  };
}