/**
 * Compile-time IPC schema. Every channel is intentionally listed: adding a
 * runtime constant without adding its tuple/result here is a type error.
 */
import type { AudioProcessRequest } from '../../src/core/creative/audioTools';
import type { ClipExtractionOptions } from '../../src/core/creative/clipExtraction';
import type { EditProject } from '../../src/core/creative/editProject';
import type { MultitrackProject } from '../../src/core/creative/multitrackProject';
import type { SlideshowRenderFormat } from '../../src/core/creative/slideshowRender';
import type { SlideshowProject, SlideshowTemplate } from '../../src/core/creative/slideshowProject';
import type { ChatContext } from '../../src/core/services/ai/GeminiService';
import type { VideoCrop } from '../../src/core/services/video/VideoEngine';
import type { AIChatMessage, AIConfigureRequest } from '../creative/ai-service';
import type { AudioToolJobSnapshot } from '../creative/audio-tools-service';
import type { BurstFrameRequest, ContactSheetRequest, SaveFrameRequest } from '../creative/capture-service';
import type { ExportJobSnapshot, ExportRequest } from '../creative/export-service';
import type { FFmpegProgress } from '../creative/ffmpeg-service';
import type { NewProjectRequest, SaveProjectRequest } from '../creative/project-service';
import type { BeginRecordingRequest } from '../creative/recording-service';
import type { DesktopCaptureOperation, DesktopCaptureOperationResult, RegionAspectPreset } from '../creative/region-capture-service';
import type { SlideshowRenderSnapshot } from '../creative/slideshow-render-service';
import type { SlideshowAssetFamily } from '../creative/slideshow-asset-service';
import type { LibraryQuery, ScanProgress } from '../library/library-service';
import type { ImageLayer, ImageTask, ImageBlendMode, ImageTransform, LayerMask } from '../../src/core/image-studio/document/schema';
import type { ExportPlan } from '../../src/core/image-studio/export/export';
import type { AIImageProvenance } from '../../src/core/image-studio/document/schema';
import type { DeferredAiJob } from '../../src/core/image-studio/ai/offline';

export type StructuredValue =
  | string
  | number
  | boolean
  | null
  | Uint8Array
  | ArrayBuffer
  | StructuredValue[]
  | object;

export type StructuredObject = object;
export type OptionalObject = object | undefined;
export type VoidResult = void;

export interface InvokeArgumentMap {
  'ai-secure:cancel': [];
  'ai-secure:chat': [message: string, history?: AIChatMessage[]];
  'ai-secure:clear': [];
  'ai-secure:configure': [request: AIConfigureRequest];
  'ai-secure:settings': [];
  'ai-secure:test': [];
  'ai:analyze-media': [filePath: string];
  'ai:chat': [message: string, context?: ChatContext];
  'ai:generate-playlist': [mood: string, count?: number];
  'ai:recommendations': [basedOn: string[]];
  'audio-tools:analyze': [sourcePath: string];
  'audio-tools:cancel': [jobId: string];
  'audio-tools:jobs': [];
  'audio-tools:process': [request: AudioProcessRequest];
  'audio:balance': [balance: number];
  'audio:dsp': [enabled: boolean];
  'audio:effect': [effect: string, params: StructuredValue];
  'audio:equalizer': [bands: number[]];
  'audio:muted': [muted: boolean];
  'audio:settings': [];
  'audio:visualizer': [];
  'audio:volume': [volume: number];
  'capture:choose-default-directory': [];
  'capture:contact-sheet': [request: ContactSheetRequest];
  'capture:copy-frame': [dataUrl: string];
  'capture:desktop': [request: DesktopCaptureOperation];
  'capture:desktop-sources': [];
  'capture:get-default-directory': [];
  'capture:recent': [];
  'capture:save-burst': [frames: BurstFrameRequest[]];
  'capture:save-frame': [request: SaveFrameRequest];
  'capture:show-item': [filePath: string];
  'clip:cancel': [jobId: string];
  'clip:extract': [inputPath: string, options: ClipExtractionOptions];
  'clip:show-item': [outputPath: string];
  'creative:open-media': [];
  'creative:path-to-media-url': [filePath: string];
  'creative:request-media-permission': [];
  'editor:autosave': [project: EditProject];
  'editor:clear-recent-projects': [];
  'editor:new-project': [request: NewProjectRequest];
  'editor:open-project': [];
  'editor:open-recent': [filePath: string];
  'editor:recent-projects': [];
  'editor:recover-autosaves': [];
  'editor:save-project': [request: SaveProjectRequest];
  'export:cancel': [jobId: string];
  'export:capabilities': [];
  'export:jobs': [];
  'export:presets': [];
  'export:probe': [filePath: string];
  'export:select-source': [];
  'export:start': [request: ExportRequest];
  'file:authorize-dropped': [filePath: string];
  'file:delete': [filePath: string];
  'file:exists': [filePath: string];
  'file:media-info': [filePath: string];
  'file:open': [options?: object];
  'file:open-directory': [options?: object];
  'file:open-multiple': [options?: object];
  'file:read': [filePath: string];
  'file:save': [options?: object];
  'file:scan': [dirPath: string, recursive?: boolean];
  'file:stats': [filePath: string];
  'file:write': [filePath: string, data: string | Buffer];
  'library:add-history': [mediaPath: string, position: number];
  'library:cancel-scan': [jobId: string];
  'library:choose-folder': [];
  'library:create-playlist': [name: string, items?: string[]];
  'library:delete-playlist': [id: string];
  'library:folders': [];
  'library:get-favorites': [];
  'library:get-history': [limit?: number];
  'library:get-media': [filters?: object];
  'library:get-playlists': [];
  'library:open-item': [filePath: string];
  'library:query': [request: LibraryQuery];
  'library:remove-folder': [folderPath: string, removeIndexedMedia?: boolean];
  'library:scan': [folderPath: string];
  'library:search': [query: string];
  'library:set-favorite': [filePath: string, favorite: boolean];
  'library:statistics': [];
  'library:toggle-favorite': [mediaPath: string];
  'library:update-playback': [filePath: string, position: number, duration: number, completed?: boolean];
  'library:update-playlist': [id: string, updates: object];
  'multitrack:autosave': [project: MultitrackProject];
  'multitrack:clear-recent': [];
  'multitrack:create': [name: string];
  'multitrack:open': [];
  'multitrack:open-recent': [filePath: string];
  'multitrack:recent': [];
  'multitrack:recoveries': [];
  'multitrack:save': [project: MultitrackProject, filePath?: string, saveAs?: boolean];
  'player:load': [filePath: string];
  'player:loop': [loop: boolean];
  'player:muted': [muted: boolean];
  'player:next': [];
  'player:pause': [];
  'player:play': [];
  'player:previous': [];
  'player:rate': [rate: number];
  'player:seek': [time: number];
  'player:shuffle': [shuffle: boolean];
  'player:state': [];
  'player:stop': [];
  'player:volume': [volume: number];
  'recording-region:select': [sourceId: string, aspectPreset?: RegionAspectPreset];
  'recording:append': [sessionId: string, chunk: ArrayBuffer | Uint8Array];
  'recording:begin': [request: BeginRecordingRequest];
  'recording:cancel': [sessionId: string];
  'recording:finish': [sessionId: string];
  'recording:list': [];
  'recording:pause': [sessionId: string];
  'recording:resume': [sessionId: string];
  'recording:show-item': [filePath: string];
  'settings:export': [];
  'settings:get': [key: string, defaultValue?: StructuredValue];
  'settings:get-all': [];
  'settings:import': [data: string];
  'settings:reset': [key?: string];
  'settings:set': [key: string, value: StructuredValue];
  'slideshow:autosave': [project: SlideshowProject];
  'slideshow:cancel-render': [jobId: string];
  'slideshow:clear-recent': [];
  'slideshow:create': [name: string, template: SlideshowTemplate];
  'slideshow:import-files': [];
  'slideshow:import-folder': [];
  'slideshow:open': [];
  'slideshow:open-output': [jobId: string];
  'slideshow:open-recent': [filePath: string];
  'slideshow:preflight': [project: SlideshowProject];
  'slideshow:recent': [];
  'slideshow:recover-backup': [originalPath: string, quarantinePath: string, backupPath: string];
  'slideshow:recoveries': [];
  'slideshow:relink-file': [family: SlideshowAssetFamily];
  'slideshow:relink-folder': [project: SlideshowProject];
  'slideshow:render': [project: SlideshowProject, format: SlideshowRenderFormat];
  'slideshow:render-jobs': [];
  'slideshow:reveal-output': [jobId: string];
  'slideshow:save': [project: SlideshowProject, filePath?: string, saveAs?: boolean];
  'subtitle:delay': [delay: number];
  'subtitle:download': [subtitleId: string];
  'subtitle:enabled': [enabled: boolean];
  'subtitle:load': [filePath: string];
  'subtitle:reload': [filePath: string, delaySeconds?: number];
  'subtitle:search': [query: string, language?: string];
  'subtitle:select': [delaySeconds?: number];
  'subtitle:settings': [];
  'subtitle:style': [style: object];
  'subtitle:sync-ai': [];
  'subtitle:translate-ai': [targetLanguage: string];
  'system:get-build-info': [];
  'system:get-ipc-health': [];
  'system:info': [];
  'system:memory': [];
  'system:open-external': [url: string];
  'system:show-item': [filePath: string];
  'video:brightness': [value: number];
  'video:contrast': [value: number];
  'video:crop': [crop: VideoCrop | null];
  'video:gamma': [value: number];
  'video:hue': [value: number];
  'video:saturation': [value: number];
  'video:screenshot': [];
  'video:settings': [];
  'video:zoom': [zoom: number];
  'window:always-on-top': [alwaysOnTop: boolean];
  'window:close': [];
  'window:fullscreen': [fullscreen: boolean];
  'window:is-fullscreen': [];
  'window:is-maximized': [];
  'window:maximize': [];
  'window:minimize': [];
  // Image Studio
  'image-studio:create': [request: { title?: string; width?: number; height?: number; backgroundMode?: string; backgroundColor?: string; applicationVersion?: string }];
  'image-studio:open': [filePath: string];
  'image-studio:save': [filePath?: string];
  'image-studio:save-as': [filePath: string];
  'image-studio:close': [filePath?: string];
  'image-studio:get-current': [];
  'image-studio:recent': [];
  'image-studio:migrate': [filePath: string];
  'image-studio:validate': [filePath: string];
  'image-studio:recover': [filePath: string];
  'image-studio:create-layer': [layer: ImageLayer];
  'image-studio:delete-layer': [layerId: string];
  'image-studio:duplicate-layer': [layerId: string];
  'image-studio:rename-layer': [layerId: string, name: string];
  'image-studio:reorder-layers': [layerIds: string[]];
  'image-studio:group-layers': [layerIds: string[], groupName?: string];
  'image-studio:ungroup-layers': [groupLayerId: string];
  'image-studio:set-visibility': [layerId: string, visible: boolean];
  'image-studio:set-locked': [layerId: string, locked: boolean];
  'image-studio:set-opacity': [layerId: string, opacity: number];
  'image-studio:set-blend-mode': [layerId: string, blendMode: ImageBlendMode];
  'image-studio:set-transform': [layerId: string, transform: ImageTransform];
  'image-studio:add-mask': [layerId: string, mask: LayerMask];
  'image-studio:update-mask': [layerId: string, mask: Partial<LayerMask>];
  'image-studio:remove-mask': [layerId: string];
  'image-studio:apply-adjustment': [layerId: string, adjustmentType: string, parameters: object];
  'image-studio:undo': [];
  'image-studio:redo': [];
  'image-studio:can-undo': [];
  'image-studio:can-redo': [];
  'image-studio:create-checkpoint': [];
  'image-studio:import-image': [filePath: string];
  'image-studio:import-as-layer': [filePath: string];
  'image-studio:export-document': [options?: ExportPlan];
  'image-studio:export-flattened': [options: ExportPlan];
  'image-studio:export-layer': [layerId: string, options: ExportPlan];
  'image-studio:inspect-format': [filePath: string];
  'image-studio:autosave-status': [filePath: string];
  'image-studio:trigger-autosave': [filePath: string];
  'image-studio:recovery-sessions': [filePath: string];
  'image-studio:restore-recovery': [recoveryPath: string];
  'image-studio:discard-recovery': [recoveryPath: string];
  'image-studio:list-providers': [];
  'image-studio:provider-status': [];
  'image-studio:list-models': [task?: ImageTask];
  'image-studio:refresh-models': [];
  'image-studio:validate-credential': [provider: string, apiKey: string];
  'image-studio:set-credential': [provider: string, apiKey: string, scopes?: string[]];
  'image-studio:remove-credential': [provider: string];
  'image-studio:create-job': [job: Omit<DeferredAiJob, 'jobId' | 'enqueuedAt' | 'attempt' | 'reason'> & { jobId?: string }];
  'image-studio:cancel-job': [jobId: string];
  'image-studio:retry-job': [jobId: string];
  'image-studio:get-job': [jobId: string];
  'image-studio:list-jobs': [];
  'image-studio:remove-job': [jobId: string];
  'image-studio:import-result': [jobId: string, accept: boolean];
}

export interface InvokeResultMap {
  'ai-secure:cancel': boolean; 'ai-secure:chat': string; 'ai-secure:clear': object; 'ai-secure:configure': object; 'ai-secure:settings': object; 'ai-secure:test': object;
  'ai:analyze-media': object; 'ai:chat': string; 'ai:generate-playlist': string[]; 'ai:recommendations': object[];
  'audio-tools:analyze': object; 'audio-tools:cancel': boolean; 'audio-tools:jobs': object[]; 'audio-tools:process': object | null;
  'audio:balance': VoidResult; 'audio:dsp': VoidResult; 'audio:effect': VoidResult; 'audio:equalizer': VoidResult; 'audio:muted': VoidResult; 'audio:settings': object; 'audio:visualizer': Uint8Array; 'audio:volume': VoidResult;
  'capture:choose-default-directory': string | null; 'capture:contact-sheet': string | null; 'capture:copy-frame': VoidResult; 'capture:desktop': DesktopCaptureOperationResult; 'capture:desktop-sources': object[]; 'capture:get-default-directory': string | null; 'capture:recent': string[]; 'capture:save-burst': string[]; 'capture:save-frame': string | null; 'capture:show-item': VoidResult;
  'clip:cancel': boolean; 'clip:extract': object | null; 'clip:show-item': VoidResult;
  'creative:open-media': object | null; 'creative:path-to-media-url': string; 'creative:request-media-permission': boolean;
  'editor:autosave': string; 'editor:clear-recent-projects': VoidResult; 'editor:new-project': object; 'editor:open-project': object | null; 'editor:open-recent': object; 'editor:recent-projects': string[]; 'editor:recover-autosaves': object[]; 'editor:save-project': string | null;
  'export:cancel': boolean; 'export:capabilities': object; 'export:jobs': object[]; 'export:presets': object[]; 'export:probe': object; 'export:select-source': string | null; 'export:start': object | null;
  'file:authorize-dropped': string; 'file:delete': boolean; 'file:exists': boolean; 'file:media-info': object; 'file:open': string | null; 'file:open-directory': string | null; 'file:open-multiple': string[]; 'file:read': Uint8Array; 'file:save': string | null; 'file:scan': string[]; 'file:stats': object; 'file:write': VoidResult;
  'library:add-history': VoidResult; 'library:cancel-scan': boolean; 'library:choose-folder': object | null; 'library:create-playlist': string; 'library:delete-playlist': VoidResult; 'library:folders': object[]; 'library:get-favorites': object[]; 'library:get-history': object[]; 'library:get-media': object[]; 'library:get-playlists': object[]; 'library:open-item': object; 'library:query': object; 'library:remove-folder': VoidResult; 'library:scan': object | VoidResult; 'library:search': object[]; 'library:set-favorite': object; 'library:statistics': object; 'library:toggle-favorite': boolean; 'library:update-playback': VoidResult; 'library:update-playlist': VoidResult;
  'multitrack:autosave': string; 'multitrack:clear-recent': VoidResult; 'multitrack:create': object; 'multitrack:open': object | null; 'multitrack:open-recent': object; 'multitrack:recent': string[]; 'multitrack:recoveries': object[]; 'multitrack:save': string | null;
  'player:load': VoidResult; 'player:loop': VoidResult; 'player:muted': VoidResult; 'player:next': VoidResult; 'player:pause': VoidResult; 'player:play': VoidResult; 'player:previous': VoidResult; 'player:rate': VoidResult; 'player:seek': VoidResult; 'player:shuffle': VoidResult; 'player:state': object; 'player:stop': VoidResult; 'player:volume': VoidResult;
  'recording-region:select': object | null; 'recording:append': object; 'recording:begin': object | null; 'recording:cancel': object; 'recording:finish': object; 'recording:list': object[]; 'recording:pause': object; 'recording:resume': object; 'recording:show-item': VoidResult;
  'settings:export': string; 'settings:get': StructuredValue | undefined; 'settings:get-all': object; 'settings:import': VoidResult; 'settings:reset': VoidResult; 'settings:set': VoidResult;
  'slideshow:autosave': string; 'slideshow:cancel-render': boolean; 'slideshow:clear-recent': VoidResult; 'slideshow:create': object; 'slideshow:import-files': object; 'slideshow:import-folder': object; 'slideshow:open': object | null; 'slideshow:open-output': VoidResult; 'slideshow:open-recent': object; 'slideshow:preflight': object[]; 'slideshow:recent': string[]; 'slideshow:recover-backup': object; 'slideshow:recoveries': object[]; 'slideshow:relink-file': object | null; 'slideshow:relink-folder': object; 'slideshow:render': object | null; 'slideshow:render-jobs': object[]; 'slideshow:reveal-output': VoidResult; 'slideshow:save': string | null;
  'subtitle:delay': VoidResult; 'subtitle:download': string; 'subtitle:enabled': VoidResult; 'subtitle:load': VoidResult; 'subtitle:reload': object; 'subtitle:search': object[]; 'subtitle:select': object | null; 'subtitle:settings': object; 'subtitle:style': VoidResult; 'subtitle:sync-ai': VoidResult; 'subtitle:translate-ai': VoidResult;
  'system:get-build-info': object; 'system:get-ipc-health': object; 'system:info': object; 'system:memory': object; 'system:open-external': VoidResult; 'system:show-item': VoidResult;
  'video:brightness': VoidResult; 'video:contrast': VoidResult; 'video:crop': VoidResult; 'video:gamma': VoidResult; 'video:hue': VoidResult; 'video:saturation': VoidResult; 'video:screenshot': string; 'video:settings': object; 'video:zoom': VoidResult;
  'window:always-on-top': VoidResult; 'window:close': VoidResult; 'window:fullscreen': VoidResult; 'window:is-fullscreen': boolean; 'window:is-maximized': boolean; 'window:maximize': VoidResult; 'window:minimize': VoidResult;
  // Image Studio
  'image-studio:create': object; 'image-studio:open': object | null; 'image-studio:save': string | null; 'image-studio:save-as': string | null; 'image-studio:close': VoidResult; 'image-studio:get-current': object | null; 'image-studio:recent': string[]; 'image-studio:migrate': object; 'image-studio:validate': object; 'image-studio:recover': object; 'image-studio:create-layer': object; 'image-studio:delete-layer': boolean; 'image-studio:duplicate-layer': object; 'image-studio:rename-layer': boolean; 'image-studio:reorder-layers': boolean; 'image-studio:group-layers': object; 'image-studio:ungroup-layers': boolean; 'image-studio:set-visibility': boolean; 'image-studio:set-locked': boolean; 'image-studio:set-opacity': boolean; 'image-studio:set-blend-mode': boolean; 'image-studio:set-transform': boolean; 'image-studio:add-mask': boolean; 'image-studio:update-mask': boolean; 'image-studio:remove-mask': boolean; 'image-studio:apply-adjustment': boolean; 'image-studio:undo': boolean; 'image-studio:redo': boolean; 'image-studio:can-undo': boolean; 'image-studio:can-redo': boolean; 'image-studio:create-checkpoint': boolean; 'image-studio:import-image': object; 'image-studio:import-as-layer': object; 'image-studio:export-document': object; 'image-studio:export-flattened': object; 'image-studio:export-layer': object; 'image-studio:inspect-format': object; 'image-studio:autosave-status': object; 'image-studio:trigger-autosave': string; 'image-studio:recovery-sessions': object[]; 'image-studio:restore-recovery': object; 'image-studio:discard-recovery': boolean; 'image-studio:list-providers': object[]; 'image-studio:provider-status': object; 'image-studio:list-models': object[]; 'image-studio:refresh-models': object[]; 'image-studio:validate-credential': object; 'image-studio:set-credential': object; 'image-studio:remove-credential': boolean; 'image-studio:create-job': string; 'image-studio:cancel-job': boolean; 'image-studio:retry-job': string; 'image-studio:get-job': object | null; 'image-studio:list-jobs': object[]; 'image-studio:remove-job': boolean; 'image-studio:import-result': object;
}

export interface InboundPayloadMap {
  'app:renderer-ready': [];
  'capture:selector-cancel': [token: string];
  'capture:selector-complete': [selection: { token: string; x: number; y: number; width: number; height: number; activation?: 'capture' | 'action-menu' }];
  'recording:selector-cancel': [token: string];
  'recording:selector-complete': [selection: { token: string; x: number; y: number; width: number; height: number }];
}

export interface OutboundPayloadMap {
  'ai:stream': [chunk: string];
  'app:open-media': [paths: string[]];
  'audio-tools:progress': [snapshot: AudioToolJobSnapshot];
  'audio:visualizer-data': [data: Uint8Array];
  'clip:progress': [progress: FFmpegProgress];
  'export:progress': [job: ExportJobSnapshot];
  'library:scan-progress': [progress: ScanProgress];
  'player:ended': [];
  'player:error': [message: string];
  'player:state-change': [state: object];
  'player:time-update': [time: number];
  'settings:change': [key: string, value: StructuredValue | undefined, oldValue: StructuredValue | undefined];
  'slideshow:render-progress': [snapshot: SlideshowRenderSnapshot];
  'system:resume': [];
  'system:suspend': [];
  'window:fullscreen-change': [fullscreen: boolean];
  'window:resize': [size: { width: number; height: number }];
  // Image Studio
  'image-studio:autosave': [filePath: string];
  'image-studio:job-progress': [job: DeferredAiJob];
  'image-studio:job-complete': [jobId: string, provenance: AIImageProvenance];
  'image-studio:job-failed': [jobId: string, error: string];
  'image-studio:recovery-available': [session: object];
}
