import type { IpcMainEvent, IpcMainInvokeEvent } from 'electron';

export interface FileDialogFilter { name: string; extensions: string[]; }
export interface FileDialogOptions { title?: string; defaultPath?: string; buttonLabel?: string; filters?: FileDialogFilter[]; }
export interface BuildIdentity { product: 'KNOUX Player X'; version: string; sha: string; branch: string; builtAt: string; packaged: boolean; electronVersion: string; }
export interface DesktopSystemInfo extends BuildIdentity { platform: NodeJS.Platform; arch: string; chromeVersion: string; nodeVersion: string; }
export interface IpcFailure { code: string; channel: string; message: string; detail?: string; }
export type IpcResult<T> = { ok: true; value: T } | { ok: false; error: IpcFailure };

export const IPC_INVOKE = {
  AI_SECURE_CANCEL: 'ai-secure:cancel',
  AI_SECURE_CHAT: 'ai-secure:chat',
  AI_SECURE_CLEAR: 'ai-secure:clear',
  AI_SECURE_CONFIGURE: 'ai-secure:configure',
  AI_SECURE_SETTINGS: 'ai-secure:settings',
  AI_SECURE_TEST: 'ai-secure:test',
  AI_ANALYZE_MEDIA: 'ai:analyze-media',
  AI_CHAT: 'ai:chat',
  AI_GENERATE_PLAYLIST: 'ai:generate-playlist',
  AI_RECOMMENDATIONS: 'ai:recommendations',
  AUDIO_TOOLS_ANALYZE: 'audio-tools:analyze',
  AUDIO_TOOLS_CANCEL: 'audio-tools:cancel',
  AUDIO_TOOLS_JOBS: 'audio-tools:jobs',
  AUDIO_TOOLS_PROCESS: 'audio-tools:process',
  AUDIO_BALANCE: 'audio:balance',
  AUDIO_DSP: 'audio:dsp',
  AUDIO_EFFECT: 'audio:effect',
  AUDIO_EQUALIZER: 'audio:equalizer',
  AUDIO_MUTED: 'audio:muted',
  AUDIO_SETTINGS: 'audio:settings',
  AUDIO_VISUALIZER: 'audio:visualizer',
  AUDIO_VOLUME: 'audio:volume',
  CAPTURE_CHOOSE_DEFAULT_DIRECTORY: 'capture:choose-default-directory',
  CAPTURE_CONTACT_SHEET: 'capture:contact-sheet',
  CAPTURE_COPY_FRAME: 'capture:copy-frame',
  CAPTURE_DESKTOP: 'capture:desktop',
  CAPTURE_DESKTOP_SOURCES: 'capture:desktop-sources',
  CAPTURE_GET_DEFAULT_DIRECTORY: 'capture:get-default-directory',
  CAPTURE_RECENT: 'capture:recent',
  CAPTURE_SAVE_BURST: 'capture:save-burst',
  CAPTURE_SAVE_FRAME: 'capture:save-frame',
  CAPTURE_SHOW_ITEM: 'capture:show-item',
  CLIP_CANCEL: 'clip:cancel',
  CLIP_EXTRACT: 'clip:extract',
  CLIP_SHOW_ITEM: 'clip:show-item',
  CREATIVE_OPEN_MEDIA: 'creative:open-media',
  CREATIVE_PATH_TO_MEDIA_URL: 'creative:path-to-media-url',
  CREATIVE_REQUEST_MEDIA_PERMISSION: 'creative:request-media-permission',
  EDITOR_AUTOSAVE: 'editor:autosave',
  EDITOR_CLEAR_RECENT_PROJECTS: 'editor:clear-recent-projects',
  EDITOR_NEW_PROJECT: 'editor:new-project',
  EDITOR_OPEN_PROJECT: 'editor:open-project',
  EDITOR_OPEN_RECENT: 'editor:open-recent',
  EDITOR_RECENT_PROJECTS: 'editor:recent-projects',
  EDITOR_RECOVER_AUTOSAVES: 'editor:recover-autosaves',
  EDITOR_SAVE_PROJECT: 'editor:save-project',
  EXPORT_CANCEL: 'export:cancel',
  EXPORT_CAPABILITIES: 'export:capabilities',
  EXPORT_JOBS: 'export:jobs',
  EXPORT_PRESETS: 'export:presets',
  EXPORT_PROBE: 'export:probe',
  EXPORT_SELECT_SOURCE: 'export:select-source',
  EXPORT_START: 'export:start',
  FILE_AUTHORIZE_DROPPED: 'file:authorize-dropped',
  FILE_DELETE: 'file:delete',
  FILE_EXISTS: 'file:exists',
  FILE_MEDIA_INFO: 'file:media-info',
  FILE_OPEN: 'file:open',
  FILE_OPEN_DIRECTORY: 'file:open-directory',
  FILE_OPEN_MULTIPLE: 'file:open-multiple',
  FILE_READ: 'file:read',
  FILE_SAVE: 'file:save',
  FILE_SCAN: 'file:scan',
  FILE_STATS: 'file:stats',
  FILE_WRITE: 'file:write',
  LIBRARY_ADD_HISTORY: 'library:add-history',
  LIBRARY_CANCEL_SCAN: 'library:cancel-scan',
  LIBRARY_CHOOSE_FOLDER: 'library:choose-folder',
  LIBRARY_CREATE_PLAYLIST: 'library:create-playlist',
  LIBRARY_DELETE_PLAYLIST: 'library:delete-playlist',
  LIBRARY_FOLDERS: 'library:folders',
  LIBRARY_GET_FAVORITES: 'library:get-favorites',
  LIBRARY_GET_HISTORY: 'library:get-history',
  LIBRARY_GET_MEDIA: 'library:get-media',
  LIBRARY_GET_PLAYLISTS: 'library:get-playlists',
  LIBRARY_OPEN_ITEM: 'library:open-item',
  LIBRARY_QUERY: 'library:query',
  LIBRARY_REMOVE_FOLDER: 'library:remove-folder',
  LIBRARY_SCAN: 'library:scan',
  LIBRARY_SEARCH: 'library:search',
  LIBRARY_SET_FAVORITE: 'library:set-favorite',
  LIBRARY_STATISTICS: 'library:statistics',
  LIBRARY_TOGGLE_FAVORITE: 'library:toggle-favorite',
  LIBRARY_UPDATE_PLAYBACK: 'library:update-playback',
  LIBRARY_UPDATE_PLAYLIST: 'library:update-playlist',
  MULTITRACK_AUTOSAVE: 'multitrack:autosave',
  MULTITRACK_CLEAR_RECENT: 'multitrack:clear-recent',
  MULTITRACK_CREATE: 'multitrack:create',
  MULTITRACK_OPEN: 'multitrack:open',
  MULTITRACK_OPEN_RECENT: 'multitrack:open-recent',
  MULTITRACK_RECENT: 'multitrack:recent',
  MULTITRACK_RECOVERIES: 'multitrack:recoveries',
  MULTITRACK_SAVE: 'multitrack:save',
  PLAYER_LOAD: 'player:load',
  PLAYER_LOOP: 'player:loop',
  PLAYER_MUTED: 'player:muted',
  PLAYER_NEXT: 'player:next',
  PLAYER_PAUSE: 'player:pause',
  PLAYER_PLAY: 'player:play',
  PLAYER_PREVIOUS: 'player:previous',
  PLAYER_RATE: 'player:rate',
  PLAYER_SEEK: 'player:seek',
  PLAYER_SHUFFLE: 'player:shuffle',
  PLAYER_STATE: 'player:state',
  PLAYER_STOP: 'player:stop',
  PLAYER_VOLUME: 'player:volume',
  RECORDING_REGION_SELECT: 'recording-region:select',
  RECORDING_APPEND: 'recording:append',
  RECORDING_BEGIN: 'recording:begin',
  RECORDING_CANCEL: 'recording:cancel',
  RECORDING_FINISH: 'recording:finish',
  RECORDING_LIST: 'recording:list',
  RECORDING_PAUSE: 'recording:pause',
  RECORDING_RESUME: 'recording:resume',
  RECORDING_SHOW_ITEM: 'recording:show-item',
  SETTINGS_EXPORT: 'settings:export',
  SETTINGS_GET: 'settings:get',
  SETTINGS_GET_ALL: 'settings:get-all',
  SETTINGS_IMPORT: 'settings:import',
  SETTINGS_RESET: 'settings:reset',
  SETTINGS_SET: 'settings:set',
  SLIDESHOW_AUTOSAVE: 'slideshow:autosave',
  SLIDESHOW_CANCEL_RENDER: 'slideshow:cancel-render',
  SLIDESHOW_CLEAR_RECENT: 'slideshow:clear-recent',
  SLIDESHOW_CREATE: 'slideshow:create',
  SLIDESHOW_OPEN: 'slideshow:open',
  SLIDESHOW_OPEN_RECENT: 'slideshow:open-recent',
  SLIDESHOW_RECENT: 'slideshow:recent',
  SLIDESHOW_RECOVERIES: 'slideshow:recoveries',
  SLIDESHOW_RENDER: 'slideshow:render',
  SLIDESHOW_RENDER_JOBS: 'slideshow:render-jobs',
  SLIDESHOW_SAVE: 'slideshow:save',
  SUBTITLE_DELAY: 'subtitle:delay',
  SUBTITLE_DOWNLOAD: 'subtitle:download',
  SUBTITLE_ENABLED: 'subtitle:enabled',
  SUBTITLE_LOAD: 'subtitle:load',
  SUBTITLE_RELOAD: 'subtitle:reload',
  SUBTITLE_SEARCH: 'subtitle:search',
  SUBTITLE_SELECT: 'subtitle:select',
  SUBTITLE_SETTINGS: 'subtitle:settings',
  SUBTITLE_STYLE: 'subtitle:style',
  SUBTITLE_SYNC_AI: 'subtitle:sync-ai',
  SUBTITLE_TRANSLATE_AI: 'subtitle:translate-ai',
  SYSTEM_INFO: 'system:info',
  SYSTEM_MEMORY: 'system:memory',
  SYSTEM_OPEN_EXTERNAL: 'system:open-external',
  SYSTEM_SHOW_ITEM: 'system:show-item',
  VIDEO_BRIGHTNESS: 'video:brightness',
  VIDEO_CONTRAST: 'video:contrast',
  VIDEO_CROP: 'video:crop',
  VIDEO_GAMMA: 'video:gamma',
  VIDEO_HUE: 'video:hue',
  VIDEO_SATURATION: 'video:saturation',
  VIDEO_SCREENSHOT: 'video:screenshot',
  VIDEO_SETTINGS: 'video:settings',
  VIDEO_ZOOM: 'video:zoom',
  WINDOW_ALWAYS_ON_TOP: 'window:always-on-top',
  WINDOW_CLOSE: 'window:close',
  WINDOW_FULLSCREEN: 'window:fullscreen',
  WINDOW_IS_FULLSCREEN: 'window:is-fullscreen',
  WINDOW_IS_MAXIMIZED: 'window:is-maximized',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_MINIMIZE: 'window:minimize',
  SYSTEM_GET_BUILD_INFO: 'system:get-build-info',
  SYSTEM_GET_IPC_HEALTH: 'system:get-ipc-health',
} as const;
export type IpcInvokeChannel = typeof IPC_INVOKE[keyof typeof IPC_INVOKE];

export const IPC_INBOUND = {
  APP_RENDERER_READY: 'app:renderer-ready',
  CAPTURE_SELECTOR_CANCEL: 'capture:selector-cancel',
  CAPTURE_SELECTOR_COMPLETE: 'capture:selector-complete',
  RECORDING_SELECTOR_CANCEL: 'recording:selector-cancel',
  RECORDING_SELECTOR_COMPLETE: 'recording:selector-complete',
} as const;
export type IpcInboundChannel = typeof IPC_INBOUND[keyof typeof IPC_INBOUND];

export const IPC_OUTBOUND = {
  AI_STREAM: 'ai:stream',
  APP_OPEN_MEDIA: 'app:open-media',
  AUDIO_TOOLS_PROGRESS: 'audio-tools:progress',
  AUDIO_VISUALIZER_DATA: 'audio:visualizer-data',
  CLIP_PROGRESS: 'clip:progress',
  EXPORT_PROGRESS: 'export:progress',
  LIBRARY_SCAN_PROGRESS: 'library:scan-progress',
  PLAYER_ENDED: 'player:ended',
  PLAYER_ERROR: 'player:error',
  PLAYER_STATE_CHANGE: 'player:state-change',
  PLAYER_TIME_UPDATE: 'player:time-update',
  SETTINGS_CHANGE: 'settings:change',
  SLIDESHOW_RENDER_PROGRESS: 'slideshow:render-progress',
  SYSTEM_RESUME: 'system:resume',
  SYSTEM_SUSPEND: 'system:suspend',
  WINDOW_FULLSCREEN_CHANGE: 'window:fullscreen-change',
  WINDOW_RESIZE: 'window:resize',
} as const;
export type IpcOutboundChannel = typeof IPC_OUTBOUND[keyof typeof IPC_OUTBOUND];

export interface SprintInvokeArguments {
  [IPC_INVOKE.SETTINGS_GET]: [key: string, defaultValue?: unknown];
  [IPC_INVOKE.SETTINGS_SET]: [key: string, value: unknown];
  [IPC_INVOKE.SETTINGS_GET_ALL]: [];
  [IPC_INVOKE.SETTINGS_RESET]: [key?: string];
  [IPC_INVOKE.SETTINGS_EXPORT]: [];
  [IPC_INVOKE.SETTINGS_IMPORT]: [data: string];
  [IPC_INVOKE.FILE_OPEN]: [options?: FileDialogOptions];
  [IPC_INVOKE.FILE_OPEN_MULTIPLE]: [options?: FileDialogOptions];
  [IPC_INVOKE.FILE_OPEN_DIRECTORY]: [options?: FileDialogOptions];
  [IPC_INVOKE.FILE_SAVE]: [options?: FileDialogOptions];
  [IPC_INVOKE.FILE_EXISTS]: [filePath: string];
  [IPC_INVOKE.SYSTEM_INFO]: [];
  [IPC_INVOKE.SYSTEM_GET_BUILD_INFO]: [];
  [IPC_INVOKE.SYSTEM_GET_IPC_HEALTH]: [];
}
export interface SprintInvokeResults {
  [IPC_INVOKE.SETTINGS_GET]: unknown;
  [IPC_INVOKE.SETTINGS_SET]: void;
  [IPC_INVOKE.SETTINGS_GET_ALL]: Record<string, unknown>;
  [IPC_INVOKE.SETTINGS_RESET]: void;
  [IPC_INVOKE.SETTINGS_EXPORT]: string;
  [IPC_INVOKE.SETTINGS_IMPORT]: void;
  [IPC_INVOKE.FILE_OPEN]: string | null;
  [IPC_INVOKE.FILE_OPEN_MULTIPLE]: string[];
  [IPC_INVOKE.FILE_OPEN_DIRECTORY]: string | null;
  [IPC_INVOKE.FILE_SAVE]: string | null;
  [IPC_INVOKE.FILE_EXISTS]: boolean;
  [IPC_INVOKE.SYSTEM_INFO]: DesktopSystemInfo;
  [IPC_INVOKE.SYSTEM_GET_BUILD_INFO]: BuildIdentity;
  [IPC_INVOKE.SYSTEM_GET_IPC_HEALTH]: unknown;
}
export type InvokeArguments<C extends IpcInvokeChannel> = C extends keyof SprintInvokeArguments ? SprintInvokeArguments[C] : unknown[];
export type InvokeResult<C extends IpcInvokeChannel> = C extends keyof SprintInvokeResults ? SprintInvokeResults[C] : unknown;
export type TypedInvokeHandler<C extends IpcInvokeChannel = IpcInvokeChannel> = (event: IpcMainInvokeEvent, ...args: InvokeArguments<C>) => InvokeResult<C> | Promise<InvokeResult<C>>;
export type TypedInboundListener = (event: IpcMainEvent, ...args: unknown[]) => void;

export interface IpcChannelDefinition { channel: string; direction: 'invoke' | 'inbound-listener' | 'outbound-event'; owner: string; exposedBy: string; arguments: string; result: string; basic: boolean; dynamic?: boolean; }
export const IPC_CHANNEL_DEFINITIONS: readonly IpcChannelDefinition[] = [
  { channel: 'ai-secure:cancel', direction: 'invoke', owner: 'secure-ai', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'ai-secure:chat', direction: 'invoke', owner: 'secure-ai', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'ai-secure:clear', direction: 'invoke', owner: 'secure-ai', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'ai-secure:configure', direction: 'invoke', owner: 'secure-ai', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'ai-secure:settings', direction: 'invoke', owner: 'secure-ai', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'ai-secure:test', direction: 'invoke', owner: 'secure-ai', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'ai:analyze-media', direction: 'invoke', owner: 'core-ai', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'ai:chat', direction: 'invoke', owner: 'core-ai', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'ai:generate-playlist', direction: 'invoke', owner: 'core-ai', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'ai:recommendations', direction: 'invoke', owner: 'core-ai', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio-tools:analyze', direction: 'invoke', owner: 'audio-tools', exposedBy: 'preload-audio-tools', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio-tools:cancel', direction: 'invoke', owner: 'audio-tools', exposedBy: 'preload-audio-tools', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio-tools:jobs', direction: 'invoke', owner: 'audio-tools', exposedBy: 'preload-audio-tools', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio-tools:process', direction: 'invoke', owner: 'audio-tools', exposedBy: 'preload-audio-tools', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio:balance', direction: 'invoke', owner: 'core-audio', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio:dsp', direction: 'invoke', owner: 'core-audio', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio:effect', direction: 'invoke', owner: 'core-audio', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio:equalizer', direction: 'invoke', owner: 'core-audio', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio:muted', direction: 'invoke', owner: 'core-audio', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio:settings', direction: 'invoke', owner: 'core-audio', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio:visualizer', direction: 'invoke', owner: 'core-audio', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'audio:volume', direction: 'invoke', owner: 'core-audio', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'capture:choose-default-directory', direction: 'invoke', owner: 'capture', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'capture:contact-sheet', direction: 'invoke', owner: 'capture', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'capture:copy-frame', direction: 'invoke', owner: 'capture', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'capture:desktop', direction: 'invoke', owner: 'capture', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'capture:desktop-sources', direction: 'invoke', owner: 'capture', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'capture:get-default-directory', direction: 'invoke', owner: 'capture', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'capture:recent', direction: 'invoke', owner: 'capture', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'capture:save-burst', direction: 'invoke', owner: 'capture', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'capture:save-frame', direction: 'invoke', owner: 'capture', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'capture:show-item', direction: 'invoke', owner: 'capture', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'clip:cancel', direction: 'invoke', owner: 'clip-extraction', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'clip:extract', direction: 'invoke', owner: 'clip-extraction', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'clip:show-item', direction: 'invoke', owner: 'clip-extraction', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'creative:open-media', direction: 'invoke', owner: 'creative', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'creative:path-to-media-url', direction: 'invoke', owner: 'creative', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'creative:request-media-permission', direction: 'invoke', owner: 'creative', exposedBy: 'preload-creative-expose', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'editor:autosave', direction: 'invoke', owner: 'editor', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'editor:clear-recent-projects', direction: 'invoke', owner: 'editor', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'editor:new-project', direction: 'invoke', owner: 'editor', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'editor:open-project', direction: 'invoke', owner: 'editor', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'editor:open-recent', direction: 'invoke', owner: 'editor', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'editor:recent-projects', direction: 'invoke', owner: 'editor', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'editor:recover-autosaves', direction: 'invoke', owner: 'editor', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'editor:save-project', direction: 'invoke', owner: 'editor', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'export:cancel', direction: 'invoke', owner: 'export', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'export:capabilities', direction: 'invoke', owner: 'export', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'export:jobs', direction: 'invoke', owner: 'export', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'export:presets', direction: 'invoke', owner: 'export', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'export:probe', direction: 'invoke', owner: 'export', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'export:select-source', direction: 'invoke', owner: 'export', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'export:start', direction: 'invoke', owner: 'export', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'file:authorize-dropped', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'file:delete', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'file:exists', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: '[filePath: string]', result: 'boolean', basic: true },
  { channel: 'file:media-info', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'file:open', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: '[options?: FileDialogOptions]', result: 'string | null', basic: true },
  { channel: 'file:open-directory', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: '[options?: FileDialogOptions]', result: 'string | null', basic: false },
  { channel: 'file:open-multiple', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: '[options?: FileDialogOptions]', result: 'string[]', basic: false },
  { channel: 'file:read', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'file:save', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: '[options?: FileDialogOptions]', result: 'string | null', basic: true },
  { channel: 'file:scan', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'file:stats', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'file:write', direction: 'invoke', owner: 'core-file', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:add-history', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:cancel-scan', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:choose-folder', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:create-playlist', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:delete-playlist', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:folders', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:get-favorites', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:get-history', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:get-media', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:get-playlists', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:open-item', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:query', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:remove-folder', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:scan', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:search', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:set-favorite', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:statistics', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:toggle-favorite', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:update-playback', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'library:update-playlist', direction: 'invoke', owner: 'creative-library', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'multitrack:autosave', direction: 'invoke', owner: 'multitrack', exposedBy: 'preload-multitrack', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'multitrack:clear-recent', direction: 'invoke', owner: 'multitrack', exposedBy: 'preload-multitrack', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'multitrack:create', direction: 'invoke', owner: 'multitrack', exposedBy: 'preload-multitrack', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'multitrack:open', direction: 'invoke', owner: 'multitrack', exposedBy: 'preload-multitrack', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'multitrack:open-recent', direction: 'invoke', owner: 'multitrack', exposedBy: 'preload-multitrack', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'multitrack:recent', direction: 'invoke', owner: 'multitrack', exposedBy: 'preload-multitrack', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'multitrack:recoveries', direction: 'invoke', owner: 'multitrack', exposedBy: 'preload-multitrack', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'multitrack:save', direction: 'invoke', owner: 'multitrack', exposedBy: 'preload-multitrack', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:load', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:loop', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:muted', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:next', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:pause', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:play', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:previous', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:rate', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:seek', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:shuffle', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:state', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:stop', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'player:volume', direction: 'invoke', owner: 'core-player', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'recording-region:select', direction: 'invoke', owner: 'recording-region', exposedBy: 'preload-recording', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'recording:append', direction: 'invoke', owner: 'recording', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'recording:begin', direction: 'invoke', owner: 'recording', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'recording:cancel', direction: 'invoke', owner: 'recording', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'recording:finish', direction: 'invoke', owner: 'recording', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'recording:list', direction: 'invoke', owner: 'recording', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'recording:pause', direction: 'invoke', owner: 'recording', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'recording:resume', direction: 'invoke', owner: 'recording', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'recording:show-item', direction: 'invoke', owner: 'recording', exposedBy: 'preload-creative', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'settings:export', direction: 'invoke', owner: 'core-settings', exposedBy: 'preload', arguments: '[]', result: 'string', basic: false },
  { channel: 'settings:get', direction: 'invoke', owner: 'core-settings', exposedBy: 'preload', arguments: '[key: string, defaultValue?: unknown]', result: 'unknown', basic: true },
  { channel: 'settings:get-all', direction: 'invoke', owner: 'core-settings', exposedBy: 'preload', arguments: '[]', result: 'Record<string, unknown>', basic: true },
  { channel: 'settings:import', direction: 'invoke', owner: 'core-settings', exposedBy: 'preload', arguments: '[data: string]', result: 'void', basic: false },
  { channel: 'settings:reset', direction: 'invoke', owner: 'core-settings', exposedBy: 'preload', arguments: '[key?: string]', result: 'void', basic: false },
  { channel: 'settings:set', direction: 'invoke', owner: 'core-settings', exposedBy: 'preload', arguments: '[key: string, value: unknown]', result: 'void', basic: true },
  { channel: 'slideshow:autosave', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'slideshow:cancel-render', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'slideshow:clear-recent', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'slideshow:create', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'slideshow:open', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'slideshow:open-recent', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'slideshow:recent', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'slideshow:recoveries', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'slideshow:render', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'slideshow:render-jobs', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'slideshow:save', direction: 'invoke', owner: 'slideshow', exposedBy: 'preload-slideshow', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:delay', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:download', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:enabled', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:load', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:reload', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:search', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:select', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:settings', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:style', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:sync-ai', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'subtitle:translate-ai', direction: 'invoke', owner: 'subtitle', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'system:info', direction: 'invoke', owner: 'core-system', exposedBy: 'preload', arguments: '[]', result: 'DesktopSystemInfo', basic: true },
  { channel: 'system:memory', direction: 'invoke', owner: 'core-system', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'system:open-external', direction: 'invoke', owner: 'core-system', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'system:show-item', direction: 'invoke', owner: 'core-system', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'video:brightness', direction: 'invoke', owner: 'core-video', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'video:contrast', direction: 'invoke', owner: 'core-video', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'video:crop', direction: 'invoke', owner: 'core-video', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'video:gamma', direction: 'invoke', owner: 'core-video', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'video:hue', direction: 'invoke', owner: 'core-video', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'video:saturation', direction: 'invoke', owner: 'core-video', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'video:screenshot', direction: 'invoke', owner: 'core-video', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'video:settings', direction: 'invoke', owner: 'core-video', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'video:zoom', direction: 'invoke', owner: 'core-video', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'window:always-on-top', direction: 'invoke', owner: 'core-window', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'window:close', direction: 'invoke', owner: 'core-window', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'window:fullscreen', direction: 'invoke', owner: 'core-window', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'window:is-fullscreen', direction: 'invoke', owner: 'core-window', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'window:is-maximized', direction: 'invoke', owner: 'core-window', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'window:maximize', direction: 'invoke', owner: 'core-window', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'window:minimize', direction: 'invoke', owner: 'core-window', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: false },
  { channel: 'system:get-build-info', direction: 'invoke', owner: 'core-system', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: true },
  { channel: 'system:get-ipc-health', direction: 'invoke', owner: 'core-system', exposedBy: 'preload', arguments: 'typed preload API tuple', result: 'typed preload API result', basic: true },
  { channel: 'app:renderer-ready', direction: 'inbound-listener', owner: 'core-app', exposedBy: 'preload', arguments: 'typed event payload', result: 'void', basic: true, dynamic: false },
  { channel: 'capture:selector-cancel', direction: 'inbound-listener', owner: 'capture-selector', exposedBy: 'preload-creative', arguments: 'typed event payload', result: 'void', basic: false, dynamic: true },
  { channel: 'capture:selector-complete', direction: 'inbound-listener', owner: 'capture-selector', exposedBy: 'preload-creative', arguments: 'typed event payload', result: 'void', basic: false, dynamic: true },
  { channel: 'recording:selector-cancel', direction: 'inbound-listener', owner: 'recording-selector', exposedBy: 'preload-recording', arguments: 'typed event payload', result: 'void', basic: false, dynamic: true },
  { channel: 'recording:selector-complete', direction: 'inbound-listener', owner: 'recording-selector', exposedBy: 'preload-recording', arguments: 'typed event payload', result: 'void', basic: false, dynamic: true },
  { channel: 'ai:stream', direction: 'outbound-event', owner: 'core-ai', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'app:open-media', direction: 'outbound-event', owner: 'app', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'audio-tools:progress', direction: 'outbound-event', owner: 'audio-tools', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'audio:visualizer-data', direction: 'outbound-event', owner: 'core-audio', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'clip:progress', direction: 'outbound-event', owner: 'clip-extraction', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'export:progress', direction: 'outbound-event', owner: 'export', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'library:scan-progress', direction: 'outbound-event', owner: 'creative-library', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'player:ended', direction: 'outbound-event', owner: 'core-player', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'player:error', direction: 'outbound-event', owner: 'core-player', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'player:state-change', direction: 'outbound-event', owner: 'core-player', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'player:time-update', direction: 'outbound-event', owner: 'core-player', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'settings:change', direction: 'outbound-event', owner: 'core-settings', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'slideshow:render-progress', direction: 'outbound-event', owner: 'slideshow', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'system:resume', direction: 'outbound-event', owner: 'core-system', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'system:suspend', direction: 'outbound-event', owner: 'core-system', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'window:fullscreen-change', direction: 'outbound-event', owner: 'core-window', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
  { channel: 'window:resize', direction: 'outbound-event', owner: 'core-window', exposedBy: 'preload subscription', arguments: 'typed event payload', result: 'void', basic: false },
] as const;

export const BASIC_INVOKE_CHANNELS = [IPC_INVOKE.SETTINGS_GET, IPC_INVOKE.SETTINGS_SET, IPC_INVOKE.SETTINGS_GET_ALL, IPC_INVOKE.FILE_OPEN, IPC_INVOKE.FILE_SAVE, IPC_INVOKE.FILE_EXISTS, IPC_INVOKE.SYSTEM_INFO, IPC_INVOKE.SYSTEM_GET_BUILD_INFO, IPC_INVOKE.SYSTEM_GET_IPC_HEALTH] as const;
export const EXPOSED_INVOKE_CHANNELS = Object.freeze(Object.values(IPC_INVOKE)) as readonly IpcInvokeChannel[];
export const DESKTOP_RUNTIME_DESCRIPTOR = Object.freeze({ edition: 'desktop' as const, product: 'KNOUX Player X' as const, bridgeVersion: 1 as const });
